#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zlocal" ]]; then
  source "${ZDOTDIR:-$HOME}/.zlocal"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zalias" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zalias"
fi

# Customize to your needs...
fpath=(~/.zsh/completion $fpath)
POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vcs)
# Hide succesful status
POWERLEVEL9K_STATUS_VERBOSE=FALSE
# Limit to the last two folders
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
# truncate_middle     = truncate middle-part
# truncate_from_right = OR from right, leaving the first X characters untouched
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

